version: '3.8'

x-pg_settings: &pg_settings
  POSTGRES_HOST: pg
  POSTGRES_PORT: 5432
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "${POSTGRES_DB}"
x-api_command: &api_command |
  yarn install --network-timeout 100000
  yarn start:dev
x-web_command: &web_command |
  yarn install --network-timeout 100000
  yarn start

volumes:
  pg_data:

services:
  api:
    image: university_api_dev
    build:
      context: ./api
      dockerfile: Dockerfile.development
    stdin_open: true
    tty: true
    command:
      - 'sh'
      - '-c'
      - *api_command
    environment:
      # api
      NODE_ENV: "${NODE_ENV:-development}"
      # pg
      <<: *pg_settings
    depends_on:
      - pg
    volumes:
      - ./api:/api
    ports:
      - '4000:4000'
  web:
    image: university_web_dev
    build:
      context: ./web
      dockerfile: Dockerfile.development
    command:
      - 'sh'
      - '-c'
      - *web_command
    environment:
      NODE_ENV: "${NODE_ENV:-development}"
    volumes:
      - ./web:/web
    ports:
      - '80:80'
  pg:
    command:
      - 'postgres'
      - '-c'
      - 'shared_preload_libraries=pg_stat_statements'
      - '-c'
      - 'pg_stat_statements.max=1000'
    environment:
      PGDATA: /var/lib/postgresql/data
      TZ: Europe/Moscow
      <<: *pg_settings
