version: '3.8'

services:
  api:
    restart: always
    
  pg:
    restart: always
    image: postgres:15.1-alpine
    command:
      - 'postgres'
      - '-c'
      - 'shared_preload_libraries=pg_stat_statements'
      - '-c'
      - 'pg_stat_statements.max=1000'
      - '-c'
      - 'max_connections=100'
    environment:
      PGDATA: /var/lib/postgresql/data
      <<: *pg_settings
